### ISSUE TITLE
支持神奇九转

### ISSUE THREAD

**Issue by axiaoxin** [axiaoxin-com/x-stock#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mojocn** [comment]
大佬  东方财富的 api url 是从什么地方获取啊, 有文档/文章链接吗?

**Comment by axiaoxin** [comment]
> 大佬 东方财富的 api url 是从什么地方获取啊, 有文档/文章链接吗?

抓包获取的

**Comment by axiaoxin** [comment]
第12行的env @GGACHA

**Comment by axiaoxin** [comment]
@GGACHA 你下的不是最新版本吗？或者看看配置文件里面sentry dsn随便填个字符串不要为空

**Comment by GGACHA** [comment]
@axiaoxin  看上去似乎引发了新的报错…好像还是时区的问题
```
goroutine 1 [running]:
time.Time.In(...)
        /usr/local/Cellar/go/1.16/libexec/src/time/time.go:1099
github.com/go-co-op/gocron.(*trueTime).Now(0x39e25a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/timeHelper.go:16 +0xd9
github.com/go-co-op/gocron.(*Scheduler).now(0x1428d650, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:886 +0x3e
github.com/go-co-op/gocron.(*Scheduler).scheduleNextRun(0x1428d650, 0x140855e0)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:149 +0x32
github.com/go-co-op/gocron.(*Scheduler).runJobs(0x1428d650, 0x1429ce70, 0x2, 0x2)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:82 +0x34
github.com/go-co-op/gocron.(*Scheduler).start(0x1428d650)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:77 +0x5f
github.com/go-co-op/gocron.(*Scheduler).StartAsync(0x1428d650)
        /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:69 +0x3a
github.com/axiaoxin-com/x-stock/cron.RunCronJobs(0x1410ac01)
        /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cron/cron.go:39 +0x262
github.com/axiaoxin-com/x-stock/cmds.ActionWebserver.func1(0x1430ac00, 0x2, 0x2)
        /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cmds/webserver_cmd.go:64 +0xe9
github.com/urfave/cli/v2.(*Command).Run(0x1440a870, 0x1430ab20, 0x0, 0x0)
        /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x3c4
github.com/urfave/cli/v2.(*App).RunContext(0x140ee000, 0x295b8ec, 0x1401e0fc, 0x140040f0, 0x2, 0x2, 0x0, 0x0)
        /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x651
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/main.go:76 +0x476
```
