### ISSUE TITLE
[Bug] v1.2.27-28 在未安装go环境的windows上读取时区出错

### ISSUE THREAD

**Issue by GGACHA** [axiaoxin-com/x-stock#29]
**Describe the bug**
v1.2.27-28 在未安装go环境的windows上读取时区出错

**To Reproduce**

1. 下载分发包解压进入目录
2. 修改config.toml中的 `env = "localhost"` 为 `env = "prod"` 方便手动更新
3. 运行 `x-stock webserver`

**Expected behavior**
正确打开服务器并下载更新数据, 成功后本地文件夹应多出下列文件.
```
    fund_4433_list.json
    fund_all_list.json
    fund_type_list.json
    industry_list.json
```
**Screenshots**
```
v1.2.27

> D:\x-stock_1.2.27_Windows_i386>x-stock.exe webserver --config "D://x-stock_1.2.27_Windows_i386//config.toml"

> {"level":"INFO","time":"2021-10-14 21:53:16.505835","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:31","msg":"load toml type config file config from D://x-stock_1.2.27_Windows_i386//","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jvcg"}
> {"level":"DEBUG","time":"2021-10-14 21:53:16.509810","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:69","msg":"Sentry use dns: 1","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jvd0"}
> {"level":"ERROR","time":"2021-10-14 21:53:16.510804","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:72","msg":"Sentry client create error:[Sentry] DsnParseError: invalid scheme","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jvdg"}
> {"level":"DEBUG","time":"2021-10-14 21:53:16.510804","logger":"logging.ctx_logger","caller":"eastmoney/industry_list.go:QueryIndustryList:39","msg":"EastMoney IndustryList https://datacenter.eastmoney.com/stock/selection/api/data/get/ begin","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jve0","reqData":{"client":"APP","source":"SELECT_SECURITIES","sty":"ALL","type":"RPTA_APP_INDUSTRY"}}
> {"level":"DEBUG","time":"2021-10-14 21:53:16.510804","logger":"logging.ctx_logger","caller":"logging@v1.2.11-0.20210710005236-5a960a1422ba/logger.go:func1:280","msg":"Running AtomicLevel HTTP server on :4870/","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jveg"}
> {"level":"DEBUG","time":"2021-10-14 21:53:16.763363","logger":"logging.ctx_logger","caller":"eastmoney/industry_list.go:QueryIndustryList:48","msg":"EastMoney IndustryList https://datacenter.eastmoney.com/stock/selection/api/data/get/ end","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jvf0","latency(ms)":250}
> {"level":"ERROR","time":"2021-10-14 21:53:16.765290","logger":"logging.ctx_logger","caller":"cmds/webserver_cmd.go:func1:59","msg":"services init error:open ./fund_all_list.json: The system cannot find the file specified.","pid":19880,"server_ip":"192.168.1.100","trace_id":"logging_c5k3cj18oau4ra62jvfg"}
> panic: The system cannot find the path specified.
> goroutine 1 [running]:
> github.com/axiaoxin-com/x-stock/cron.RunCronJobs(0x14368001)
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cron/cron.go:29 +0x2b9
> github.com/axiaoxin-com/x-stock/cmds.ActionWebserver.func1(0x14280e40, 0x2, 0x2)
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cmds/webserver_cmd.go:64 +0xe9
> github.com/urfave/cli/v2.(*Command).Run(0x140a8c60, 0x14280b40, 0x0, 0x0)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x3c4
> github.com/urfave/cli/v2.(*App).RunContext(0x14368000, 0x1e7b89c, 0x140a00b8, 0x1408a100, 0x4, 0x4, 0x0, 0x0)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x651
> github.com/urfave/cli/v2.(*App).Run(...)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/main.go:76 +0x476
```
```
v1.2.28

> D:\x-stock_1.2.28_Windows_x86_64>x-stock webserver
> {"level":"INFO","time":"2021-10-15 01:58:02.569335","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:31","msg":"load toml type config file config from ./","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7j0"}
> {"level":"DEBUG","time":"2021-10-15 01:58:02.574363","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:69","msg":"Sentry use dns: 1","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7jg"}
> {"level":"ERROR","time":"2021-10-15 01:58:02.575091","logger":"logging.ctx_logger","caller":"webserver/webserver.go:InitWithConfigFile:72","msg":"Sentry client create error:[Sentry] DsnParseError: invalid scheme","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7k0"}
> {"level":"DEBUG","time":"2021-10-15 01:58:02.576338","logger":"logging.ctx_logger","caller":"logging@v1.2.11-0.20210710005236-5a960a1422ba/logger.go:func1:280","msg":"Running AtomicLevel HTTP server on :4870/","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7l0"}
> {"level":"DEBUG","time":"2021-10-15 01:58:02.576257","logger":"logging.ctx_logger","caller":"eastmoney/industry_list.go:QueryIndustryList:39","msg":"EastMoney IndustryList https://datacenter.eastmoney.com/stock/selection/api/data/get/ begin","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7kg","reqData":{"client":"APP","source":"SELECT_SECURITIES","sty":"ALL","type":"RPTA_APP_INDUSTRY"}}
> {"level":"DEBUG","time":"2021-10-15 01:58:02.936368","logger":"logging.ctx_logger","caller":"eastmoney/industry_list.go:QueryIndustryList:48","msg":"EastMoney IndustryList https://datacenter.eastmoney.com/stock/selection/api/data/get/ end","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7lg","latency(ms)":359}
> {"level":"ERROR","time":"2021-10-15 01:58:02.938722","logger":"logging.ctx_logger","caller":"cmds/webserver_cmd.go:func1:59","msg":"services init error:open ./fund_all_list.json: The system cannot find the file specified.","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7m0"}
> {"level":"ERROR","time":"2021-10-15 01:58:02.939347","logger":"logging.ctx_logger","caller":"cron/cron.go:RunCronJobs:30","msg":"RunCronJobs time LoadLocation error:The system cannot find the path specified.","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7mg"}
> {"level":"DEBUG","time":"2021-10-15 01:58:02.940617","logger":"logging.ctx_logger","caller":"cron/cron.go:RunCronJobs:32","msg":"cron timezone:UTC","pid":14612,"server_ip":"192.168.1.100","trace_id":"logging_c5k6vah8oau3i56dg7n0"}
> panic: time: missing Location in call to Time.In
> 
> goroutine 1 [running]:
> time.Time.In(...)
>         /usr/local/Cellar/go/1.16/libexec/src/time/time.go:1099
> github.com/go-co-op/gocron.(*trueTime).Now(0x3081438, 0x0, 0x35, 0x20fef33, 0x20fef33)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/timeHelper.go:16 +0xdd
> github.com/go-co-op/gocron.(*Scheduler).now(0xc00007ec80, 0x25f4548, 0x262f860, 0x20fef33)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:886 +0x49
> github.com/go-co-op/gocron.(*Scheduler).scheduleNextRun(0xc00007ec80, 0xc00014a000)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:149 +0x47
> github.com/go-co-op/gocron.(*Scheduler).runJobs(0xc00007ec80, 0xc00008d560, 0x2, 0x2)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:82 +0x49
> github.com/go-co-op/gocron.(*Scheduler).start(0xc00007ec80)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:77 +0x85
> github.com/go-co-op/gocron.(*Scheduler).StartAsync(0xc00007ec80)
>         /Users/axiaoxin/go/pkg/mod/github.com/go-co-op/gocron@v1.6.2/scheduler.go:69 +0x51
> github.com/axiaoxin-com/x-stock/cron.RunCronJobs(0xc000085201)
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cron/cron.go:39 +0x2aa
> github.com/axiaoxin-com/x-stock/cmds.ActionWebserver.func1(0xc000094600, 0x2, 0x2)
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/cmds/webserver_cmd.go:64 +0x11a
> github.com/urfave/cli/v2.(*Command).Run(0xc0003c9440, 0xc0000944c0, 0x0, 0x0)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
> github.com/urfave/cli/v2.(*App).RunContext(0xc0003ca820, 0x1ea27a8, 0xc00002a0b8, 0xc0000623c0, 0x2, 0x2, 0x0, 0x0)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x825
> github.com/urfave/cli/v2.(*App).Run(...)
>         /Users/axiaoxin/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
>         /Users/axiaoxin/go/src/github.com/axiaoxin-com/x-stock/main.go:76 +0x54f

```

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Additional context**
https://github.com/axiaoxin-com/x-stock/issues/25

问题解决:

- 下载分发文件 [tzdata.zip](https://github.com/axiaoxin-com/x-stock/files/7348353/tzdata.zip)

- ```set "zoneinfo=tzdata.zip"``` 设置环境变量
- 再`x-stock webserver`

参考:

https://github.com/golang/go/issues/38017
https://github.com/golang/go/issues/21881
https://stackoverflow.com/questions/52489347/how-to-create-a-binary-that-contains-zoneinfo-zip

**Comment by axiaoxin** [comment]
nice. 老哥有空试下1.2.29行不行 我没有windows环境不太方便测试

**Comment by GGACHA** [comment]
> nice. 老哥有空试下1.2.29行不行 我没有windows环境不太方便测试

跑起来了, 不用手动再加环境变量了.
话说那些json要怎么转xlsx导出啊, 我这行命令似乎不太对?
```
x-stock.exe -l error exportor -f s.xlsx --filter.special_security_code_list 660001
```
```
{"level":"WARN","time":"2021-10-15 17:29:36.754615","logger":"logging.ctx_logger","caller":"logging@v1.2.11-0.20210710005236-5a960a1422ba/logger.go:SetLevel:253","msg":"Set logging atomicLevel error","pid":30460,"server_ip":"192.168.1.100","trace_id":"logging_c5kkk018oau7dv2qg7bg"}
{"level":"FATAL","time":"2021-10-15 17:29:36.988936","logger":"logging.ctx_logger","caller":"cmds/exportor.go:Export:88","msg":"no stocks data","pid":30460,"server_ip":"192.168.1.100","trace_id":"logging_c5kkk018oau7dv2qg7eg"}
```


---题外话
大佬你是标配mac吗  `_(:3|∠)_`

**Comment by axiaoxin** [comment]
exportor 只支持股票筛选结果的导出，不同公司的字段值长度不一样没有做太细致的处理。
基金的json数据现在没有直接支持导出功能，你要是想把json转成excel可以用其他工具自己转一下
可以试试这个https://github.com/axiaoxin/json2xls（不保证可用0.0）
